import { TankConfig, WeatherType } from '../types';

export interface BiomeConfig {
  id: string;
  name: string;
  weather: WeatherType;
  weatherName: string;
  skyColor: string;
  fogColor: string;
  sunColor: string;
  groundColor: string;
  cliffColor: string;
  grassColor: string;
  ambientIntensity: number;
}

export const BIOMES: BiomeConfig[] = [
  {
    id: 'green_hills',
    name: 'Verdant Hills',
    weather: 'rain',
    weatherName: 'Heavy Rainstorm',
    skyColor: '#1a2c3d',
    fogColor: '#243a4e',
    sunColor: '#bcd4e6',
    groundColor: '#2d5426',
    cliffColor: '#453526',
    grassColor: '#447833',
    ambientIntensity: 0.6,
  },
  {
    id: 'martian_desert',
    name: 'Red Canyon',
    weather: 'sandstorm',
    weatherName: 'Desert Sandstorm',
    skyColor: '#5c2214',
    fogColor: '#7a3b2b',
    sunColor: '#ffad73',
    groundColor: '#a8432a',
    cliffColor: '#572214',
    grassColor: '#bd5332',
    ambientIntensity: 0.72,
  },
  {
    id: 'arctic_tundra',
    name: 'Frost Peak',
    weather: 'snow',
    weatherName: 'Snow Blizzard',
    skyColor: '#0b1d3a',
    fogColor: '#1e4266',
    sunColor: '#c8ebff',
    groundColor: '#dbeaf8',
    cliffColor: '#344e63',
    grassColor: '#f4faff',
    ambientIntensity: 0.85,
  },
  {
    id: 'volcanic_caldera',
    name: 'Volcanic Ridge',
    weather: 'volcanic',
    weatherName: 'Ash & Embers',
    skyColor: '#2b0909',
    fogColor: '#4a1212',
    sunColor: '#ff5500',
    groundColor: '#1c1615',
    cliffColor: '#38120c',
    grassColor: '#6e1d10',
    ambientIntensity: 0.65,
  },
  {
    id: 'cyber_wasteland',
    name: 'Neon Metropolis',
    weather: 'clear',
    weatherName: 'Starlit Clear',
    skyColor: '#0d081f',
    fogColor: '#1b1236',
    sunColor: '#ff00aa',
    groundColor: '#181a29',
    cliffColor: '#0c0e17',
    grassColor: '#00f0ff',
    ambientIntensity: 0.6,
  },
];

export const TANK_ROSTER: TankConfig[] = [
  {
    id: 'abrams',
    name: 'Abrams M1',
    tagline: 'Heavy Military Juggernaut',
    description: 'Classic heavy armor tank equipped with high-explosive armor-piercing artillery and guided cruise missiles.',
    primaryColor: '#2f4f2f',
    secondaryColor: '#1c331c',
    accentColor: '#e0a020',
    glowColor: '#ffc83b',
    category: 'Heavy',
    modelType: 'abrams',
    stats: {
      health: 1200,
      damage: 85,
      mobility: 70,
      armor: 90,
    },
    weapons: [
      {
        id: 'abrams_shell',
        name: 'Armor Piercer',
        description: 'Heavy ballistic shell with standard explosive radius and direct kinetic damage.',
        icon: 'Crosshair',
        damage: 280,
        blastRadius: 2.6,
        ammo: -1,
        maxAmmo: -1,
        type: 'standard',
        color: '#ffcc00',
        trailColor: '#ff9900',
        explosionColor: '#ff5500',
        soundType: 'cannon',
      },
      {
        id: 'abrams_cluster',
        name: 'Triple Volley',
        description: 'Splits mid-flight into 3 separate high-explosive warheads covering a wide area.',
        icon: 'Boxes',
        damage: 130, // per warhead = 390 total
        blastRadius: 2.2,
        ammo: 5,
        maxAmmo: 5,
        type: 'cluster',
        splitCount: 3,
        color: '#ff6600',
        trailColor: '#ff4400',
        explosionColor: '#ff2200',
        soundType: 'rocket',
      },
      {
        id: 'abrams_tomahawk',
        name: 'Tomahawk Cruise',
        description: 'Devastating cruise warhead that carves a massive crater on impact.',
        icon: 'Flame',
        damage: 480,
        blastRadius: 4.5,
        craterDepthScale: 1.6,
        ammo: 2,
        maxAmmo: 2,
        type: 'standard',
        color: '#ff2200',
        trailColor: '#ff8800',
        explosionColor: '#ff1100',
        soundType: 'cannon',
      },
    ],
  },
  {
    id: 'frost',
    name: 'Frostbite',
    tagline: 'Cryogenic Siege Engine',
    description: 'Harnesses sub-zero liquid nitrogen to freeze opponents, impairing movement and shattering terrain into icy chasms.',
    primaryColor: '#1b4d6b',
    secondaryColor: '#0c2438',
    accentColor: '#58d3f7',
    glowColor: '#00f7ff',
    category: 'Cryo',
    modelType: 'frost',
    stats: {
      health: 1050,
      damage: 80,
      mobility: 80,
      armor: 75,
    },
    weapons: [
      {
        id: 'frost_shard',
        name: 'Cryo Spike',
        description: 'High velocity ice dart that chills the target and deals solid piercing damage.',
        icon: 'Snowflake',
        damage: 260,
        blastRadius: 2.2,
        ammo: -1,
        maxAmmo: -1,
        type: 'standard',
        color: '#7ee8fa',
        trailColor: '#00c3ff',
        explosionColor: '#a1f1ff',
        soundType: 'freeze',
      },
      {
        id: 'frost_freeze_blast',
        name: 'Glacial Nova',
        description: 'Detonates a sub-zero vortex that freezes enemy tracks, preventing driving for 1 turn.',
        icon: 'ShieldAlert',
        damage: 310,
        blastRadius: 3.5,
        ammo: 4,
        maxAmmo: 4,
        type: 'freeze',
        color: '#00d2ff',
        trailColor: '#b8f2ff',
        explosionColor: '#5ce1e6',
        soundType: 'freeze',
      },
      {
        id: 'frost_blizzard',
        name: 'Blizzard Hail',
        description: 'Fires an airburst shell splitting into 5 freezing icicle bomblets.',
        icon: 'Wind',
        damage: 90,
        blastRadius: 2.0,
        ammo: 2,
        maxAmmo: 2,
        type: 'cluster',
        splitCount: 5,
        color: '#e0f7fa',
        trailColor: '#80deea',
        explosionColor: '#4dd0e1',
        soundType: 'freeze',
      },
    ],
  },
  {
    id: 'buratino',
    name: 'Buratino MLRS',
    tagline: 'Multi-Rocket Barrage System',
    description: 'Heavy rocket artillery chassis capable of rapid-fire multi-missile barrages that blanket battlefields in fire.',
    primaryColor: '#7a5a22',
    secondaryColor: '#45300d',
    accentColor: '#f59e0b',
    glowColor: '#ffb703',
    category: 'Artillery',
    modelType: 'buratino',
    stats: {
      health: 1100,
      damage: 95,
      mobility: 65,
      armor: 70,
    },
    weapons: [
      {
        id: 'buratino_rocket',
        name: 'Thermobaric Rocket',
        description: 'Heavy solid-fuel rocket with high explosive shockwave.',
        icon: 'Zap',
        damage: 270,
        blastRadius: 2.8,
        ammo: -1,
        maxAmmo: -1,
        type: 'standard',
        color: '#fb923c',
        trailColor: '#ea580c',
        explosionColor: '#f97316',
        soundType: 'rocket',
      },
      {
        id: 'buratino_salvo',
        name: 'Katyusha Salvo',
        description: 'Fires 4 rapid-fire rockets in a tight deadly ballistic arc.',
        icon: 'ChevronsUp',
        damage: 105, // 420 total
        blastRadius: 2.0,
        ammo: 4,
        maxAmmo: 4,
        type: 'split',
        splitCount: 4,
        color: '#f97316',
        trailColor: '#c2410c',
        explosionColor: '#ea580c',
        soundType: 'rocket',
      },
      {
        id: 'buratino_napalm',
        name: 'Napalm Inferno',
        description: 'Giant incendiary cluster that rains fire over the target coordinates.',
        icon: 'Flame',
        damage: 120,
        blastRadius: 2.4,
        ammo: 2,
        maxAmmo: 2,
        type: 'cluster',
        splitCount: 6,
        color: '#dc2626',
        trailColor: '#f97316',
        explosionColor: '#b91c1c',
        soundType: 'rocket',
      },
    ],
  },
  {
    id: 'spectre',
    name: 'Spectre Void',
    tagline: 'Alien Plasma Skimmer',
    description: 'Futuristic antigravity hover-tank harnessing dark matter plasma bolts and localized gravity singularities.',
    primaryColor: '#2b1055',
    secondaryColor: '#12042b',
    accentColor: '#c084fc',
    glowColor: '#a855f7',
    category: 'Future',
    modelType: 'spectre',
    stats: {
      health: 1000,
      damage: 90,
      mobility: 95,
      armor: 65,
    },
    weapons: [
      {
        id: 'spectre_plasma',
        name: 'Plasma Bolt',
        description: 'High-density ionized plasma sphere unaffected by minor wind.',
        icon: 'Sparkles',
        damage: 290,
        blastRadius: 2.4,
        ammo: -1,
        maxAmmo: -1,
        type: 'plasma',
        color: '#c084fc',
        trailColor: '#9333ea',
        explosionColor: '#d8b4fe',
        soundType: 'plasma',
      },
      {
        id: 'spectre_rift',
        name: 'Void Singularity',
        description: 'Implosion bomb that pulls ground and enemy toward epicenter, dealing severe collapse damage.',
        icon: 'Disc',
        damage: 380,
        blastRadius: 3.8,
        ammo: 3,
        maxAmmo: 3,
        type: 'standard',
        color: '#a855f7',
        trailColor: '#6b21a8',
        explosionColor: '#581c87',
        soundType: 'plasma',
      },
      {
        id: 'spectre_scatter',
        name: 'Quantum Scatter',
        description: 'Splits into 4 homing plasma spikes that saturate the area.',
        icon: 'Orbit',
        damage: 110,
        blastRadius: 2.1,
        ammo: 2,
        maxAmmo: 2,
        type: 'split',
        splitCount: 4,
        color: '#e879f9',
        trailColor: '#c026d3',
        explosionColor: '#f0abfc',
        soundType: 'plasma',
      },
    ],
  },
  {
    id: 'atomic',
    name: 'Atomic Behemoth',
    tagline: 'Nuclear Warhead Platform',
    description: 'Catastrophic nuclear weapons carrier engineered to atomize opposing battalions with mini-nukes.',
    primaryColor: '#364022',
    secondaryColor: '#1c2410',
    accentColor: '#84cc16',
    glowColor: '#a3e635',
    category: 'Biohazard',
    modelType: 'atomic',
    stats: {
      health: 1300,
      damage: 100,
      mobility: 50,
      armor: 95,
    },
    weapons: [
      {
        id: 'atomic_isotope',
        name: 'Isotope Shell',
        description: 'Depleted uranium shell with heavy ground impact and radiation burst.',
        icon: 'Radio',
        damage: 300,
        blastRadius: 2.7,
        ammo: -1,
        maxAmmo: -1,
        type: 'standard',
        color: '#a3e635',
        trailColor: '#65a30d',
        explosionColor: '#84cc16',
        soundType: 'cannon',
      },
      {
        id: 'atomic_dirty',
        name: 'Dirty Warhead',
        description: 'Contaminates a huge zone with toxic fallout and high impact damage.',
        icon: 'Biohazard',
        damage: 370,
        blastRadius: 3.6,
        ammo: 3,
        maxAmmo: 3,
        type: 'standard',
        color: '#84cc16',
        trailColor: '#4d7c0f',
        explosionColor: '#bef264',
        soundType: 'cannon',
      },
      {
        id: 'atomic_nuke',
        name: 'Tactical Nuke',
        description: 'Apocalyptic nuclear missile with colossal blast radius, giant mushroom plume, and crater devastation.',
        icon: 'Atom',
        damage: 550,
        blastRadius: 6.0,
        craterDepthScale: 2.2,
        ammo: 1,
        maxAmmo: 1,
        type: 'nuke',
        color: '#eab308',
        trailColor: '#ca8a04',
        explosionColor: '#facc15',
        soundType: 'nuke',
      },
    ],
  },
  {
    id: 'helios',
    name: 'Helios Sunfire',
    tagline: 'Solar Laser Dreadnought',
    description: 'Golden vanguard drawing power from concentrated solar arrays to fire piercing orbital beams and solar flares.',
    primaryColor: '#6b4f14',
    secondaryColor: '#362604',
    accentColor: '#facc15',
    glowColor: '#fde047',
    category: 'Energy',
    modelType: 'helios',
    stats: {
      health: 1100,
      damage: 90,
      mobility: 75,
      armor: 80,
    },
    weapons: [
      {
        id: 'helios_flare',
        name: 'Solar Flare',
        description: 'Incandescent solar core shell that detonates in a blinding golden flash.',
        icon: 'Sun',
        damage: 280,
        blastRadius: 2.5,
        ammo: -1,
        maxAmmo: -1,
        type: 'standard',
        color: '#fde047',
        trailColor: '#eab308',
        explosionColor: '#facc15',
        soundType: 'laser',
      },
      {
        id: 'helios_laser',
        name: 'Solar Cannon',
        description: 'Instant pinpoint concentrated light beam that cuts through all terrain directly to the target.',
        icon: 'Zap',
        damage: 340,
        blastRadius: 1.8,
        ammo: 4,
        maxAmmo: 4,
        type: 'laser',
        color: '#fef08a',
        trailColor: '#facc15',
        explosionColor: '#ffffff',
        soundType: 'laser',
      },
      {
        id: 'helios_orbital',
        name: 'Orbital Strike',
        description: 'Calls down a satellite beam from orbit directly onto the trajectory endpoint.',
        icon: 'Target',
        damage: 460,
        blastRadius: 4.0,
        ammo: 2,
        maxAmmo: 2,
        type: 'airstrike',
        color: '#ffffff',
        trailColor: '#fde047',
        explosionColor: '#fef08a',
        soundType: 'laser',
      },
    ],
  },
  {
    id: 'coalition',
    name: 'Coalition Dual-Cannon',
    tagline: 'Twin Barrel Superheavy',
    description: 'Formidable armored fortress sporting dual-synchronized barrels that deliver double the kinetic firepower.',
    primaryColor: '#3b3b3b',
    secondaryColor: '#1f1f1f',
    accentColor: '#ef4444',
    glowColor: '#f87171',
    category: 'Heavy',
    modelType: 'coalition',
    stats: {
      health: 1350,
      damage: 85,
      mobility: 60,
      armor: 100,
    },
    weapons: [
      {
        id: 'coalition_twin',
        name: 'Twin Shells',
        description: 'Fires two heavy cannon shells in rapid sequence.',
        icon: 'Copy',
        damage: 170, // 340 total
        blastRadius: 2.3,
        ammo: -1,
        maxAmmo: -1,
        type: 'split',
        splitCount: 2,
        color: '#ef4444',
        trailColor: '#b91c1c',
        explosionColor: '#dc2626',
        soundType: 'cannon',
      },
      {
        id: 'coalition_bounce',
        name: 'Bouncing Grenade',
        description: 'Skips and ricochets along terrain slopes before detonating for high surprise damage.',
        icon: 'RotateCw',
        damage: 360,
        blastRadius: 3.0,
        ammo: 4,
        maxAmmo: 4,
        type: 'bouncing',
        color: '#f87171',
        trailColor: '#ef4444',
        explosionColor: '#b91c1c',
        soundType: 'cannon',
      },
      {
        id: 'coalition_mortar',
        name: 'Siege Mortar',
        description: 'High-arc ballistic mortar creating an enormous crater and high blast area.',
        icon: 'Target',
        damage: 470,
        blastRadius: 4.8,
        ammo: 2,
        maxAmmo: 2,
        type: 'mortar',
        color: '#fca5a5',
        trailColor: '#ef4444',
        explosionColor: '#7f1d1d',
        soundType: 'cannon',
      },
    ],
  },
  {
    id: 'toxicator',
    name: 'Toxicator 9000',
    tagline: 'Corrosive Slime Artillery',
    description: 'Shoots acidic chemical ordnance that melts through armor and erodes terrain layers.',
    primaryColor: '#14422e',
    secondaryColor: '#092117',
    accentColor: '#10b981',
    glowColor: '#34d399',
    category: 'Biohazard',
    modelType: 'toxicator',
    stats: {
      health: 1100,
      damage: 85,
      mobility: 80,
      armor: 70,
    },
    weapons: [
      {
        id: 'toxic_glob',
        name: 'Acid Glob',
        description: 'Corrosive acid payload that splashes on contact.',
        icon: 'Droplet',
        damage: 270,
        blastRadius: 2.5,
        ammo: -1,
        maxAmmo: -1,
        type: 'standard',
        color: '#34d399',
        trailColor: '#059669',
        explosionColor: '#10b981',
        soundType: 'plasma',
      },
      {
        id: 'toxic_shower',
        name: 'Acid Rain',
        description: 'Splits high in the atmosphere into 5 corrosive drizzle droplets.',
        icon: 'CloudRain',
        damage: 90,
        blastRadius: 2.0,
        ammo: 4,
        maxAmmo: 4,
        type: 'cluster',
        splitCount: 5,
        color: '#6ee7b7',
        trailColor: '#10b981',
        explosionColor: '#047857',
        soundType: 'plasma',
      },
      {
        id: 'toxic_core',
        name: 'Meltdown Slurry',
        description: 'Heavy chemical core that carves a deep toxic crater.',
        icon: 'Skull',
        damage: 440,
        blastRadius: 4.2,
        craterDepthScale: 1.8,
        ammo: 2,
        maxAmmo: 2,
        type: 'standard',
        color: '#059669',
        trailColor: '#10b981',
        explosionColor: '#064e3b',
        soundType: 'plasma',
      },
    ],
  },
  {
    id: 'dubstep',
    name: 'Bass Cannon 3000',
    tagline: 'Sonic Frequency Disruptor',
    description: 'Pumps pulsating acoustic shockwaves and bass drops that rattle the landscape and blast tanks into the air.',
    primaryColor: '#3b0764',
    secondaryColor: '#1e0236',
    accentColor: '#ec4899',
    glowColor: '#f472b6',
    category: 'Energy',
    modelType: 'dubstep',
    stats: {
      health: 1050,
      damage: 90,
      mobility: 85,
      armor: 70,
    },
    weapons: [
      {
        id: 'sonic_pulse',
        name: 'Sub Pulse',
        description: 'Rhythmic sonic wave projectile that punches through air.',
        icon: 'Volume2',
        damage: 275,
        blastRadius: 2.6,
        ammo: -1,
        maxAmmo: -1,
        type: 'plasma',
        color: '#ec4899',
        trailColor: '#db2777',
        explosionColor: '#f472b6',
        soundType: 'plasma',
      },
      {
        id: 'sonic_drop',
        name: 'Bass Drop',
        description: 'Unleashes a massive acoustic shockwave that ripples the terrain.',
        icon: 'Activity',
        damage: 390,
        blastRadius: 4.2,
        ammo: 3,
        maxAmmo: 3,
        type: 'standard',
        color: '#f472b6',
        trailColor: '#be185d',
        explosionColor: '#ec4899',
        soundType: 'cannon',
      },
      {
        id: 'sonic_wobble',
        name: 'Wobble Barrage',
        description: 'Tri-frequency sonic burst that detonates in rapid succession.',
        icon: 'Radio',
        damage: 135,
        blastRadius: 2.3,
        ammo: 2,
        maxAmmo: 2,
        type: 'split',
        splitCount: 3,
        color: '#fb7185',
        trailColor: '#e11d48',
        explosionColor: '#f43f5e',
        soundType: 'plasma',
      },
    ],
  },
  {
    id: 'tiger',
    name: 'Panzer VI Tiger I',
    tagline: 'Legendary German Heavy War Machine',
    description: 'Iconic German heavy tank engineered with impenetrable 100mm frontal armor, the devastating 8.8 cm KwK 36 cannon, and high-velocity modern German kinetic dart shells.',
    primaryColor: '#706854', // Dunkelgelb German Camouflage
    secondaryColor: '#423d32', // Darker Panzer shadow
    accentColor: '#c29b38', // Brass / Gold insignia
    glowColor: '#eab308',
    category: 'Historical',
    modelType: 'tiger',
    stats: {
      health: 1350,
      damage: 96,
      mobility: 65,
      armor: 98,
    },
    weapons: [
      {
        id: 'tiger_pzgr39',
        name: '8.8cm PzGr 39',
        description: 'Historic German 88mm Armor-Piercing Capped ballistic shell. Extreme muzzle velocity and lethal direct impact kinetic damage.',
        icon: 'Crosshair',
        damage: 320,
        blastRadius: 2.6,
        ammo: -1,
        maxAmmo: -1,
        type: 'standard',
        color: '#f59e0b',
        trailColor: '#d97706',
        explosionColor: '#b45309',
        soundType: 'cannon',
      },
      {
        id: 'tiger_sprgr',
        name: '8.8cm Sprgr. 43 HE',
        description: 'Heavy German Sprenggranate high-explosive blast shell with massive explosive yield and wide shockwave radius.',
        icon: 'Flame',
        damage: 380,
        blastRadius: 4.2,
        craterDepthScale: 1.5,
        ammo: 4,
        maxAmmo: 4,
        type: 'standard',
        color: '#ef4444',
        trailColor: '#dc2626',
        explosionColor: '#991b1b',
        soundType: 'cannon',
      },
      {
        id: 'tiger_gr39hl',
        name: 'Gr. 39 HL (HEAT)',
        description: 'Hohlladung shaped-charge warhead that generates a focused molten jet to melt armor and punch deep into the terrain.',
        icon: 'Zap',
        damage: 440,
        blastRadius: 3.4,
        craterDepthScale: 1.9,
        ammo: 3,
        maxAmmo: 3,
        type: 'standard',
        color: '#f97316',
        trailColor: '#ea580c',
        explosionColor: '#c2410c',
        soundType: 'cannon',
      },
      {
        id: 'tiger_dm63',
        name: 'DM63 APFSDS Sabot',
        description: 'Modern German Rheinmetall hypervelocity tungsten kinetic dart. Flies with laser-flat trajectory, zero wind deflection, and maximum penetration.',
        icon: 'Target',
        damage: 510,
        blastRadius: 2.7,
        ammo: 1,
        maxAmmo: 1,
        type: 'standard',
        isSabotDart: true,
        color: '#38bdf8',
        trailColor: '#0284c7',
        explosionColor: '#0369a1',
        soundType: 'cannon',
      },
    ],
  },
];
